name: Build App
on:
 [pull_request ,workflow_dispatch]
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK  
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant Gradle permision
        run : chmod +x gradlew    
      - name: Run Gradle  
        run: ./gradlew build
